[package]
name = "otdr-fixer"
version = "0.1.0"
authors = ["James Harrison <james@talkunafraid.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
otdrs = "1.0.0"
clap = "4.5.17"
walkdir = "2.5.0"
