name: Rust releases

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [linux, windows, macos]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/otdr-fixer
            asset_name: otdr-fixer-linux
          - name: windows
            os: windows-latest
            artifact_name: target/release/otdr-fixer.exe
            asset_name: otdr-fixer-windows
          - name: macos
            os: macos-latest
            artifact_name: target/release/otdr-fixer
            asset_name: otdr-fixer-macos

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        run: |
          cargo update
          cargo build --release --locked

      - name: Upload binaries to release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.artifact_name }}
